name: maris
favicon: null
layout_spectrum: 0.595408694120124
typography_spectrum: 0.8163020052015781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.40564055764116347
  lightness: 0.4809099407866597
  saturation: 0.5256384420208633
  rhythmicContrast: 0.05816175579093397
purpose: []
